from __future__ import annotations

from scripts.content import ROOT, load_records, research_scope
from scripts.generate_site import generate_all


def test_generated_listing_counts_match_records() -> None:
    generate_all()
    themes = (ROOT / "generated/home-themes.qmd").read_text(encoding="utf-8")
    people = (ROOT / "generated/people.qmd").read_text(encoding="utf-8")
    projects = (ROOT / "generated/projects.qmd").read_text(encoding="utf-8")
    publications = (ROOT / "generated/publications.qmd").read_text(encoding="utf-8")
    reviewed = (ROOT / "generated/research-watch-reviewed.qmd").read_text(encoding="utf-8")
    candidates = (ROOT / "generated/research-watch-candidates.qmd").read_text(encoding="utf-8")

    assert themes.count('<article class="theme-card">') == len(research_scope()["themes"])
    assert people.count('<article class="record-card">') == len(load_records("data/people"))
    assert projects.count('<article class="record-card">') == len(load_records("data/projects"))
    assert publications.count('<article class="record-card">') == len(load_records("data/publications"))
    assert reviewed.count('<article class="watch-card reviewed">') == len(load_records("data/research-watch/approved"))
    assert candidates.count('<article class="watch-card candidate">') == len(load_records("data/research-watch/candidates"))


def test_candidate_listing_has_non_endorsement_language() -> None:
    generate_all()
    page = (ROOT / "research-watch/index.qmd").read_text(encoding="utf-8")
    assert "not endorsed by the lab" in page
    assert "Automatically identified" in page


def test_generated_fragments_are_marked() -> None:
    generate_all()
    for path in (ROOT / "generated").glob("*.qmd"):
        assert path.read_text(encoding="utf-8").startswith("<!-- Generated by")
