#!/usr/bin/env python3
"""Generate deterministic Quarto fragments and canonical detail/theme pages."""

from __future__ import annotations

import html
import json
import shutil
import sys
from collections import Counter
from pathlib import Path
from typing import Any

try:
    from .content import ROOT, load_records, research_scope, theme_index
    from .validate_content import validate_all
except ImportError:
    from content import ROOT, load_records, research_scope, theme_index
    from validate_content import validate_all

OUT = ROOT / "generated"
FULL_DISCLOSURE = "Current Conversations uses automated searches and AI-generated classification, grouping and summaries to identify recent material connected to the lab's research themes. Sources may include academic papers, policy reports, news, blogs, data tools and public posts. Items have not normally been reviewed by a member of the Cities and Climate Learning Lab, and inclusion does not imply endorsement. Coverage is selective and uneven, and summaries may contain errors or omit important context. Please consult the original sources."
FIXTURE_DISCLOSURE = "This captured fixture was assembled without AI generation to test presentation and governance controls. It has not been reviewed by the lab, is not endorsed, and is not evidence of a live retrieval. Consult the original source."
ENV_LABELS = {
    "academic-research": "Academic research", "policy-and-institutions": "Policy and institutions",
    "news-and-analysis": "News and analysis", "blogs-and-commentary": "Blogs and commentary",
    "data-and-tools": "Data and tools", "bluesky": "Bluesky",
}
ROLE_LABELS = {
    "primary-research": "Original research", "official-policy-source": "Official policy source",
    "official-announcement": "Official announcement", "dataset-or-tool": "Dataset or tool",
    "news-reporting": "Reporting", "independent-analysis": "Independent analysis",
    "research-commentary": "Research commentary", "practitioner-commentary": "Practitioner commentary",
    "public-discussion": "Public discussion",
}


def esc(value: Any) -> str:
    return html.escape(str(value), quote=True)


def write_fragment(name: str, body: str) -> None:
    path = OUT / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("<!-- Generated by scripts/generate_site.py; do not edit. -->\n```{=html}\n" + body.rstrip() + "\n```\n", encoding="utf-8")


def write_page(path: Path, title: str, description: str, body: str, *, canonical: str | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    canonical_line = f'canonical-url: "{canonical}"\n' if canonical else ""
    path.write_text(f'---\ntitle: "{title.replace(chr(34), chr(39))}"\ndescription: "{description.replace(chr(34), chr(39))}"\n{canonical_line}---\n\n<!-- Generated by scripts/generate_site.py; do not edit. -->\n\n{body.rstrip()}\n', encoding="utf-8")


def load_json_records(directory: Path) -> list[dict[str, Any]]:
    return [json.loads(path.read_text(encoding="utf-8")) for path in sorted(directory.glob("*.json"))]


def labels(ids: list[str]) -> list[str]:
    themes = theme_index()
    return [themes[item]["name"] for item in ids]


def tags(items: list[str], css: str = "tag-list") -> str:
    return f'<ul class="{css}">' + "".join(f"<li>{esc(item)}</li>" for item in items) + "</ul>"


def linked_tags(primary: str | None, secondary: list[str]) -> str:
    themes = theme_index()
    values = ([(primary, "Primary")] if primary else []) + [(item, "Related") for item in secondary]
    if not values:
        return '<ul class="tag-list"><li>Cross-cutting or not classified by lab theme</li></ul>'
    return '<ul class="tag-list">' + "".join(f'<li><a href="/research/{esc(item)}.html">{esc(themes[item]["name"])}</a><span class="sr-only"> ({kind})</span></li>' for item, kind in values) + "</ul>"


def provenance_label(cluster: dict[str, Any]) -> str:
    if cluster.get("ai_provenance", {}).get("used") is True:
        return "Identified and summarized using AI · not reviewed by the lab"
    if cluster.get("captured_fixture"):
        return "Captured fixture · no AI generation recorded · not reviewed by the lab"
    return "Automatically identified · no AI generation recorded · not reviewed by the lab"


def provenance_disclosure(cluster: dict[str, Any]) -> str:
    return FULL_DISCLOSURE if cluster.get("ai_provenance", {}).get("used") is True else FIXTURE_DISCLOSURE


def record_card(record: dict[str, Any], kind: str) -> str:
    relation = record.get("relationship_to_lab", "").replace("-", " ").title()
    meta = " · ".join(filter(None, [relation, record.get("status"), record.get("venue"), str(record.get("publication_date", ""))[:4]]))
    return f'''<article class="record-card" data-themes="{esc(' '.join([record['primary_theme'], *record['secondary_themes']]))}">
  <p class="record-kicker">{esc(meta.replace('-', ' ').title())}</p>
  <h3><a href="/{kind}/{esc(record['record_id'])}.html">{esc(record['title'])}</a></h3>
  <p>{esc(record.get('summary') or record.get('abstract_summary'))}</p>
  {linked_tags(record['primary_theme'], record['secondary_themes'])}
</article>'''


def conversation_card(cluster: dict[str, Any], sources: dict[str, dict[str, Any]]) -> str:
    principal = sources[cluster["principal_source_id"]]
    linked = [sources[source_id] for source_id in cluster["linked_source_ids"]]
    all_sources = [principal, *linked]
    source_links = "".join(f'<li><span class="source-role">{esc(ROLE_LABELS.get(source["source_role"], source["source_role"]))}</span> <a href="{esc(source["original_url"])}">{esc(source["title"])}</a> <span>— {esc(source["publisher_or_platform"])}</span></li>' for source in all_sources)
    grouped = '<span class="grouped-label">Related sources grouped automatically</span>' if linked else '<span class="entry-kind">Standalone conversation entry</span>'
    compact = provenance_label(cluster)
    fixture = '<span class="fixture-label">Captured fixture</span>' if cluster["captured_fixture"] else ""
    environments = " ".join(cluster["source_environments"])
    theme_values = [item for item in [cluster['primary_theme'], *cluster['secondary_themes']] if item]
    return f'''<article class="conversation-card" data-theme="{esc(' '.join(theme_values))}" data-environment="{esc(environments)}" data-geography="{esc(' '.join(cluster['geographies']))}" data-date="{esc(cluster['date_most_recently_observed'])}" data-kind="{'cluster' if linked else 'standalone'}">
  <p class="conversation-flags"><span class="status-badge unreviewed">{esc(compact)}</span>{fixture}{grouped}</p>
  <h3><a href="/current-conversations/{esc(cluster['slug'])}.html">{esc(cluster['public_title'])}</a></h3>
  <p class="record-meta">{esc(cluster['date_most_recently_observed'])} · {esc(ENV_LABELS[principal['source_environment']])} · {esc(ROLE_LABELS.get(principal['source_role'], principal['source_role']))}</p>
  <p>{esc(cluster['summary'])}</p>
  <p><strong>Why it may be relevant</strong><br>{esc(cluster['reason_for_relevance'])}</p>
  <p class="evidence-limitation"><strong>Evidence and interpretation limitation:</strong> {esc(cluster['limitations'])}</p>
  {linked_tags(cluster['primary_theme'], cluster['secondary_themes'])}
  <details><summary>Original sources and roles</summary><ul class="source-list">{source_links}</ul><p>{esc(cluster['agreement_disagreement_uncertainty'])}</p></details>
  <span class="sr-only">{esc(provenance_disclosure(cluster))}</span>
</article>'''


def select_home_clusters(clusters: list[dict[str, Any]], sources: dict[str, dict[str, Any]]) -> list[dict[str, Any]]:
    chosen: list[dict[str, Any]] = []
    domains: Counter[str] = Counter()
    lab_count = 0
    for cluster in sorted(clusters, key=lambda item: item["date_most_recently_observed"], reverse=True):
        if not cluster["homepage_eligible"] or cluster["publication_decision"] != "published":
            continue
        principal = sources[cluster["principal_source_id"]]
        if domains[principal["source_domain"]] >= 2:
            continue
        if principal["lab_affiliated"] and lab_count >= 1:
            continue
        chosen.append(cluster); domains[principal["source_domain"]] += 1
        lab_count += int(principal["lab_affiliated"])
        if len(chosen) == 6:
            break
    return chosen


def generate_themes(projects: list[dict[str, Any]], publications: list[dict[str, Any]], clusters: list[dict[str, Any]], sources: dict[str, dict[str, Any]]) -> None:
    themes = research_scope()["themes"]
    home = ['<ol class="learning-cycle" aria-label="Four connected research questions">']
    details = ['<div class="detail-grid connected-theme-list">']
    legacy_routes = {
        "urban-climate-learning": "geographies-of-climate-learning",
        "evidence-infrastructure-tools": "where-new-evidence-matters",
        "climate-governance-delivery": "modes-of-climate-delivery",
        "co-benefits-place-based-valuation": "consequences-for-people-and-places",
        "just-transitions-workforce": "consequences-for-people-and-places",
        "canadian-climate-policy": "modes-of-climate-delivery",
    }
    for index, theme in enumerate(themes, 1):
        badge = '<span class="theme-status developing">Developing</span>' if theme["status"] == "developing" else ""
        home.append(f'''<li class="cycle-stage"><article><span class="theme-number">0{index}</span>{badge}<p class="cycle-role">{esc(theme['cycle_role'])}</p><h3><a href="/research/{esc(theme['id'])}.html">{esc(theme['name'])}</a></h3><p class="guiding-question">{esc(theme['guiding_question'])}</p><p>{esc(theme['definition'])}</p><p><a class="text-link" href="/research/{esc(theme['id'])}.html">Explore this question <span aria-hidden="true">→</span></a></p></article></li>''')
        details.append(f'''<article class="detail-card" id="{esc(theme['id'])}"><div class="detail-index">0{index}</div><div>{badge}<p class="cycle-role">{esc(theme['cycle_role'])}</p><h2><a href="/research/{esc(theme['id'])}.html">{esc(theme['name'])}</a></h2><p class="guiding-question">{esc(theme['guiding_question'])}</p><p>{esc(theme['definition'])}</p><p><a class="text-link" href="/research/{esc(theme['id'])}.html">View the theme programme →</a></p></div><aside class="detail-meta"><strong>Geographic priorities</strong><span>{esc(', '.join(theme['geographical_priorities']))}</span><strong>Methods of interest</strong><span>{esc(', '.join(theme['methodological_interests']))}</span></aside></article>''')
        core_projects = [record for record in projects if record["primary_theme"] == theme["id"]]
        related_projects = [record for record in projects if theme["id"] in record["secondary_themes"]]
        core_pubs = [record for record in publications if record["primary_theme"] == theme["id"] and record["featured"]]
        related_pubs = [record for record in publications if theme["id"] in record["secondary_themes"] and record["featured"]]
        recent = [record for record in clusters if record["publication_decision"] == "published" and (record["primary_theme"] == theme["id"] or theme["id"] in record["secondary_themes"])][:3]
        def links(items: list[dict[str, Any]], kind: str) -> str:
            return '<div class="compact-list">' + ''.join(f'<p><a href="/{kind}/{esc(item["record_id"])}.html">{esc(item["title"])}</a></p>' for item in items) + '</div>' if items else '<p class="empty-compact">No verified records are published in this view yet.</p>'
        recent_html = '<div class="compact-list">' + ''.join(f'<p><a href="/current-conversations/{esc(item["slug"])}.html">{esc(item["public_title"])}</a><br><span>{esc(provenance_label(item))}</span></p>' for item in recent) + '</div>' if recent else '<p class="empty-compact">No recent Current Conversations entry is assigned here.</p>'
        other_themes = [item for item in themes if item["id"] != theme["id"]]
        connections = "\n".join(f'- [{item["name"]}](/research/{item["id"]}.html) — {item["cycle_role"]}' for item in other_themes)
        questions = "\n".join(f"- {item}" for item in theme["included_questions"])
        boundaries = "\n".join(f"- {item}" for item in theme["exclusions"])
        body = f'''<p class="cycle-role">{theme['cycle_role']}</p>

<p class="page-deck"><strong>{theme['guiding_question']}</strong></p>

{theme['definition']}

::: {{.notice}}
**Part of a connected learning cycle.** Projects and cities may enter at different points. Evidence about consequences can revise judgements about existing knowledge and where new evidence matters.
:::

## Questions the lab investigates

{questions}

## Analytical boundary

{boundaries}

## Lab research: core projects

```{{=html}}
{links(core_projects, 'projects')}
```

## Lab research: related projects

```{{=html}}
{links(related_projects, 'projects')}
```

## Lab-authored publications and outputs

```{{=html}}
{links(core_pubs + related_pubs, 'publications')}
```

## Connections across the programme

{connections}

## External horizon scanning: Current Conversations

These externally sourced items are separate from the lab's projects and outputs. Classification indicates topical connection, not endorsement, evidential quality or applicability to another city.

```{{=html}}
{recent_html}
```

[How Current Conversations works](/current-conversations/how-it-works.html).'''
        write_page(ROOT / "research" / f"{theme['id']}.qmd", theme["name"], theme["definition"], body, canonical=f"/research/{theme['id']}.html")
    for old_id, new_id in legacy_routes.items():
        destination = theme_index()[new_id]
        redirect_body = f'''<p class="page-deck">This former theme route has moved into the lab's four-theme research programme.</p>

[Continue to **{destination['name']}**](/research/{new_id}.html).

This transition page preserves older internal and shared links. It does not define a separate research theme.'''
        write_page(ROOT / "research/themes" / f"{old_id}.qmd", "Research theme route updated", destination["definition"], redirect_body, canonical=f"/research/{new_id}.html")
    home.append('<li class="cycle-return"><strong>Consequences generate further learning.</strong> Outcomes, burdens and unresolved questions return to the first two stages as new evidence and revised judgements.</li></ol>')
    details.append('<div class="cycle-return-note"><strong>The return matters:</strong> consequences generate new evidence, expose unresolved questions and change what other places can plausibly learn.</div></div>')
    write_fragment("home-themes.qmd", "\n".join(home)); write_fragment("research-themes.qmd", "\n".join(details))


def generate_people() -> None:
    cards = ['<div class="record-list">']
    for person in load_records("data/people"):
        links = " · ".join(f'<a href="{esc(item["url"])}">{esc(item["label"])}</a>' for item in person["profile_links"])
        cards.append(f'''<article class="record-card person-card"><p class="record-kicker">{esc(person['academic_title'])} · {esc(person['lab_role'])}</p><h2>{esc(person['name'])}</h2><p>{esc(person['short_bio'])}</p><p><a href="mailto:{esc(person['email'])}">{esc(person['email'])}</a></p><p>{links}</p>{tags(labels(person['themes']))}</article>''')
    cards.append("</div>"); write_fragment("people.qmd", "\n".join(cards))


def generate_projects(projects: list[dict[str, Any]], publications: list[dict[str, Any]]) -> None:
    groups = [("Current lab research", "current-lab-research"), ("Foundational and prior work", "foundational-prior-work"), ("Associated collaborations", "associated-collaboration")]
    listing = []
    for heading, key in groups:
        items = [record for record in projects if record["relationship_to_lab"] == key]
        if items: listing.append(f'<section class="relationship-group"><h2>{heading}</h2><div class="record-list">' + ''.join(record_card(item, "projects") for item in items) + '</div></section>')
    write_fragment("projects.qmd", "".join(listing))
    publications_by_id = {record["record_id"]: record for record in publications}
    for record in projects:
        sources = "\n".join((f'- [{item["label"]}]({item["url"]})' if item.get("url") else f'- {item["label"]}') + f' — verified {item["retrieved_date"]}' for item in record["authoritative_sources"])
        connections = "\n".join(f'- [{publications_by_id[item]["title"]}](/publications/{item}.html)' for item in record["connected_publications"] if item in publications_by_id) or "No connected publication is recorded."
        learning_fields = [
            ("Decision or problem", "decision_or_problem"),
            ("Existing evidence", "existing_evidence"),
            ("Transfer conditions", "transfer_conditions"),
            ("Consequential uncertainty", "consequential_uncertainty"),
            ("Delivery conditions", "delivery_conditions"),
            ("Consequences examined", "consequences_examined"),
            ("Evidence status", "evidence_status"),
            ("Claim boundaries", "claim_boundaries"),
            ("Next learning question", "next_learning_question"),
        ]
        learning = "\n\n".join(f"**{label}:** {record[key]}" for label, key in learning_fields if record.get(key))
        secondary = ", ".join(f'[{theme_index()[item]["name"]}](/research/{item}.html)' for item in record["secondary_themes"]) or "No secondary theme assigned."
        facets = f"**Geographies:** {', '.join(record['geographies'])}<br>\n**Climate domains:** {', '.join(record['climate_domains'])}<br>\n**Sectors:** {', '.join(record['sectors'])}<br>\n**Methods:** {', '.join(record['methods'])}"
        learning_section = f"## How this project contributes to climate learning\n\n**Primary theme:** [{theme_index()[record['primary_theme']]['name']}](/research/{record['primary_theme']}.html)\n\n**Secondary connections:** {secondary}\n\n{learning}\n\n### Research facets\n\n{facets}" if learning else ""
        body = f'''<p class="page-deck">{record['summary']}</p>

**Status:** {record['status'].replace('-', ' ').title()}<br>
**Relationship to the lab:** {record['relationship_to_lab'].replace('-', ' ').title()} — {record['relationship_note']}<br>
**Primary theme:** [{theme_index()[record['primary_theme']]['name']}](/research/{record['primary_theme']}.html)

{learning_section}

## Research questions

{chr(10).join('- ' + item for item in record['research_questions'])}

## Connected publications

{connections}

## Authoritative sources

{sources}
'''
        write_page(ROOT / "projects" / f"{record['record_id']}.qmd", record["title"], record["summary"], body)


def generate_publications(publications: list[dict[str, Any]]) -> None:
    selected = [record for record in publications if record["featured"]]
    write_fragment("publications-selected.qmd", '<div class="record-list">' + ''.join(record_card(record, "publications") for record in selected) + '</div>')
    by_year: dict[str, list[dict[str, Any]]] = {}
    for record in publications: by_year.setdefault(record["publication_date"][:4], []).append(record)
    complete = []
    for year in sorted(by_year, reverse=True):
        complete.append(f'<section class="bibliography-year" id="year-{year}"><h2>{year}</h2><div class="bibliography-list">')
        for record in sorted(by_year[year], key=lambda item: item["title"]):
            status = "Peer review not verified" if record["peer_review_status"] == "unknown" else record["peer_review_status"].replace("-", " ").title()
            mdpi = '<span class="status-badge neutral">Complete record only · not selected</span>' if record.get("mdpi_excluded") else ""
            complete.append(f'<article class="bibliography-entry" data-year="{year}" data-type="{esc(record["publication_type"])}"><h3><a href="/publications/{esc(record["record_id"])}.html">{esc(record["title"])}</a></h3><p>{esc(", ".join(record["authors"]))}</p><p class="record-meta">{esc(record["venue"])} · {esc(record["publication_type"].replace("-", " ").title())} · {esc(status)} {mdpi}</p></article>')
        complete.append('</div></section>')
    write_fragment("publications-complete.qmd", "".join(complete))
    complete_body = '''<p class="page-deck">A complete verified record of Andrew Sudmant's publications and outputs, distinct from the smaller selected set.</p>

Records are grouped by year. Historic outputs are labelled as foundational or prior work and are not presented as products of the new lab. Bibliographic metadata comes from authoritative identifier records, not AI generation.

```{=html}
<form class="publication-filters" data-publication-filters aria-label="Filter verified publications and outputs">
  <label>Keyword <input type="search" name="query" autocomplete="off"></label>
  <label>Type <select name="type"><option value="">All output types</option><option value="article">Articles</option><option value="preprint">Preprints</option><option value="chapter">Chapters</option><option value="report">Reports</option><option value="dataset">Datasets</option><option value="other">Other</option></select></label>
  <button type="reset">Clear</button><output data-publication-count aria-live="polite"></output>
</form>
```

{{< include ../generated/publications-complete.qmd >}}

[Return to selected publications](/publications.html).'''
    write_page(ROOT / "publications/complete.qmd", "Verified publications and outputs", "Verified publications and outputs by Andrew Sudmant, with authoritative-source provenance.", complete_body)
    for record in publications:
        identifier = f'**DOI:** [{record["doi"]}](https://doi.org/{record["doi"]})' if record.get("doi") else f'**Other identifier:** {", ".join(record["other_identifiers"])}' if record.get("other_identifiers") else '**Stable identifier:** none assigned by the authoritative source; use the original-source URL.'
        mdpi_note = "\n\n::: {.notice}\nThis verified MDPI-authored work is retained in the complete scholarly record. By owner policy it is not selected, featured or eligible for Current Conversations.\n:::" if record.get("mdpi_excluded") else ""
        body = f'''<p class="page-deck">{record['abstract_summary']}</p>

**Authors:** {', '.join(record['authors'])}<br>
**Published:** {record['publication_date']} · {record['venue']} · {record['publication_type'].replace('-', ' ').title()}<br>
**Relationship to the lab:** {record['relationship_to_lab'].replace('-', ' ').title()} — {record['relationship_note']}<br>
{identifier}

> {record['citation']}

[Open the original source]({record['url']}){mdpi_note}

## Metadata provenance

Metadata sources: {', '.join(record['metadata_sources'])} · last verified {record['last_verified_date']} · status: {record['verification_status'].replace('-', ' ')}. Dates are displayed only to the precision supplied by the verified record. No AI-generated bibliographic metadata is used.'''
        write_page(ROOT / "publications" / f"{record['record_id']}.qmd", record["title"], record["abstract_summary"], body)


def generate_conversations(clusters: list[dict[str, Any]], source_list: list[dict[str, Any]]) -> None:
    sources = {record["source_id"]: record for record in source_list}
    published = sorted([record for record in clusters if record["publication_decision"] == "published"], key=lambda item: item["date_most_recently_observed"], reverse=True)
    write_fragment("current-conversations-feed.qmd", '<div class="conversation-grid" id="conversation-results">' + ''.join(conversation_card(record, sources) for record in published) + '</div>')
    home = select_home_clusters(published, sources)
    write_fragment("home-current-conversations.qmd", '<div class="conversation-grid home-conversations">' + ''.join(conversation_card(record, sources) for record in home) + '</div>')
    for cluster in published:
        principal = sources[cluster["principal_source_id"]]
        linked = [sources[source_id] for source_id in cluster["linked_source_ids"]]
        def source_section(source: dict[str, Any], heading: str) -> str:
            fixture = " Captured fixture for private calibration." if source["captured_fixture"] else ""
            return f'''### {heading}: {source['title']}

- **Environment:** {ENV_LABELS[source['source_environment']]}
- **Role:** {ROLE_LABELS.get(source['source_role'], source['source_role'])}
- **Author or organisation:** {', '.join(source['authors_or_organisation'])}
- **Published:** {source['publication_date']}
- **Evidence accessed:** {', '.join(source['evidence_basis'])}
- **Access limitation:** {source['evidence_limitations']}{fixture}

[Open this original source]({source['original_url']})'''
        sections = [source_section(principal, "Principal source")] + [source_section(source, "Also discussed in") for source in linked]
        fixture_notice = "\n\n::: {.notice}\n**Private calibration fixture.** One or more sources were captured to test mixed-source presentation because the paid web adapter was unavailable. This entry is not evidence of a live automated retrieval.\n:::" if cluster["captured_fixture"] else ""
        body = f'''<p class="page-deck">{cluster['discussion_statement']}</p>

<p class="status-badge unreviewed">{provenance_label(cluster)}</p>
{'<p class="grouped-label">Related sources grouped automatically</p>' if linked else ''}

## What is being discussed

{cluster['summary']}

## Why it may be relevant

{cluster['reason_for_relevance']}

## Evidence, interpretation and uncertainty

{cluster['limitations']}

{cluster['agreement_disagreement_uncertainty']}{fixture_notice}

## Sources

{(chr(10) * 2).join(sections)}

## Grouping provenance

**Rationale:** {cluster['clustering']['rationale']}<br>
**Principal-source choice:** {cluster['clustering']['principal_source_rationale']}<br>
**Method/version:** {cluster['clustering']['method']} · {cluster['clustering']['version']}<br>
**Confidence:** {cluster['clustering']['confidence']:.2f}

[How Current Conversations works](/current-conversations/how-it-works.html) · [Request a correction](/contact.html)'''
        write_page(ROOT / "current-conversations" / f"{cluster['slug']}.qmd", cluster["public_title"], cluster["discussion_statement"], body, canonical=f"/current-conversations/{cluster['slug']}.html")
    feed_items = [{"id": cluster["cluster_id"], "url": f"/current-conversations/{cluster['slug']}.html", "title": cluster["public_title"], "content_text": cluster["summary"], "date_published": cluster["date_first_observed"], "date_modified": cluster["date_most_recently_observed"], "external_url": sources[cluster["principal_source_id"]]["original_url"], "tags": [item for item in [cluster["primary_theme"], *cluster["secondary_themes"]] if item]} for cluster in published]
    (ROOT / "current-conversations/feed.json").write_text(json.dumps({"version": "https://jsonfeed.org/version/1.1", "title": "Cities & Climate Learning Lab — Current Conversations", "home_page_url": "/current-conversations/", "feed_url": "/current-conversations/feed.json", "items": feed_items}, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    rss_items = "".join(f'<item><guid>{esc(item["id"])}</guid><title>{esc(item["title"])}</title><link>{esc(item["url"])}</link><description>{esc(item["content_text"])}</description><pubDate>{esc(item["date_published"])}</pubDate></item>' for item in feed_items)
    (ROOT / "current-conversations/feed.xml").write_text('<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>Cities &amp; Climate Learning Lab — Current Conversations</title><link>/current-conversations/</link><description>Recent conversations connected to the lab research themes.</description>' + rss_items + '</channel></rss>\n', encoding="utf-8")


def generate_all() -> None:
    errors = validate_all()
    if errors: raise ValueError("content validation failed:\n" + "\n".join(errors))
    OUT.mkdir(exist_ok=True)
    for legacy in (
        "home-watch.qmd", "publications.qmd", "research-watch-automated.qmd",
        "research-watch-candidates.qmd", "research-watch-reviewed.qmd",
    ):
        (OUT / legacy).unlink(missing_ok=True)
    for directory in (ROOT / "projects", ROOT / "publications", ROOT / "research/themes"):
        if directory.exists(): shutil.rmtree(directory)
    for path in (ROOT / "research").glob("*.qmd"):
        if path.name != "our-approach.qmd": path.unlink()
    for path in (ROOT / "current-conversations").glob("*.qmd"):
        if path.name not in {"index.qmd", "how-it-works.qmd"}: path.unlink()
    projects = load_records("data/projects")
    complete = json.loads((ROOT / "reports/content/publication-complete-inventory.json").read_text(encoding="utf-8"))["records"]
    sources = load_json_records(ROOT / "data/current-conversations/generated/sources")
    clusters = load_json_records(ROOT / "data/current-conversations/generated/clusters")
    generate_themes(projects, complete, clusters, {record["source_id"]: record for record in sources})
    generate_people(); generate_projects(projects, complete); generate_publications(complete); generate_conversations(clusters, sources)


def main() -> int:
    try: generate_all()
    except ValueError as exc:
        print(exc); return 1
    print("Generated canonical listings, publication views, conversation clusters, feeds and theme pages.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
