#!/usr/bin/env python3
"""Generate deterministic Quarto fragments from validated YAML records."""

from __future__ import annotations

import html
import sys
from pathlib import Path
from typing import Any

try:
    from .content import ROOT, load_records, research_scope, theme_index
    from .validate_content import validate_all
except ImportError:  # Direct script execution.
    from content import ROOT, load_records, research_scope, theme_index
    from validate_content import validate_all

OUT = ROOT / "generated"


def esc(value: Any) -> str:
    return html.escape(str(value), quote=True)


def write(name: str, body: str) -> None:
    notice = "<!-- Generated by scripts/generate_site.py; do not edit. -->\n"
    raw_html = "```{=html}\n" + body.rstrip() + "\n```\n"
    (OUT / name).write_text(notice + raw_html, encoding="utf-8")


def labels(theme_ids: list[str]) -> list[str]:
    themes = theme_index()
    return [themes[theme_id]["name"] for theme_id in theme_ids]


def tags(items: list[str]) -> str:
    return '<ul class="tag-list">' + "".join(f"<li>{esc(item)}</li>" for item in items) + "</ul>"


def generate_themes() -> None:
    themes = research_scope()["themes"]
    cards = ['<div class="theme-grid">']
    for index, theme in enumerate(themes, start=1):
        cards.append(
            f'''<article class="theme-card">
  <span class="theme-number">0{index}</span>
  <h3>{esc(theme["name"])}</h3>
  <p>{esc(theme["definition"])}</p>
</article>'''
        )
    cards.append("</div>")
    write("home-themes.qmd", "\n".join(cards))

    details = ['<div class="detail-grid">']
    for index, theme in enumerate(themes, start=1):
        question_list = "".join(f"<li>{esc(item)}</li>" for item in theme["included_questions"])
        concept_tags = tags(theme["initial_search_concepts"])
        geo = ", ".join(theme["geographical_priorities"])
        methods = ", ".join(theme["methodological_interests"])
        exclusions = " ".join(theme["exclusions"])
        details.append(
            f'''<article class="detail-card" id="{esc(theme["id"])}">
  <div class="detail-index">0{index}</div>
  <div>
    <h2>{esc(theme["name"])}</h2>
    <p>{esc(theme["definition"])}</p>
    <strong>Included questions</strong>
    <ul>{question_list}</ul>
    <strong>Initial search concepts</strong>
    {concept_tags}
  </div>
  <aside class="detail-meta">
    <strong>Geographical priorities</strong>
    <span>{esc(geo)}</span>
    <strong>Methodological interests</strong>
    <span>{esc(methods)}</span>
    <strong>Exclusions</strong>
    <span>{esc(exclusions)}</span>
    <strong>Representative examples</strong>
    <span>Placeholders requiring owner review.</span>
  </aside>
</article>'''
        )
    details.append("</div>")
    write("research-themes.qmd", "\n".join(details))


def generate_people() -> None:
    cards = ['<div class="record-list">']
    for person in load_records("data/people"):
        theme_tags = tags(labels(person["themes"]))
        cards.append(
            f'''<article class="record-card">
  <span class="fixture-label">Placeholder · owner review required</span>
  <h2>{esc(person["name"])}</h2>
  <p class="record-kicker">{esc(person["role"])}</p>
  <p>{esc(person["bio"])}</p>
  {theme_tags}
</article>'''
        )
    cards.append("</div>")
    write("people.qmd", "\n".join(cards))


def generate_projects() -> None:
    cards = ['<div class="record-list">']
    for project in load_records("data/projects"):
        cards.append(
            f'''<article class="record-card">
  <span class="fixture-label">Placeholder · {esc(project["status"])}</span>
  <h2>{esc(project["title"])}</h2>
  <p>{esc(project["summary"])}</p>
  {tags(labels(project["themes"]))}
</article>'''
        )
    cards.append("</div>")
    write("projects.qmd", "\n".join(cards))


def generate_publications() -> None:
    cards = ['<div class="record-list">']
    for item in load_records("data/publications"):
        cards.append(
            f'''<article class="record-card">
  <span class="fixture-label">Placeholder record</span>
  <h2>{esc(item["title"])}</h2>
  <p class="record-meta">{esc(", ".join(item["authors"]))} · {esc(item["year"])} · {esc(item["publication_type"].replace("-", " "))}</p>
  <p>{esc(item["abstract"])}</p>
  <p><strong>Citation:</strong> {esc(item["citation"])}</p>
  {tags(labels(item["themes"]))}
</article>'''
        )
    cards.append("</div>")
    write("publications.qmd", "\n".join(cards))


def watch_card(record: dict[str, Any], state: str) -> str:
    reviewed = state == "reviewed"
    review_label = "Human reviewed fixture" if reviewed else "Automatically identified · not reviewed"
    stable = record["stable_identifier"]
    stable_label = "No stable identifier recorded"
    if stable:
        stable_label = f'{stable["type"].upper()}: {stable["value"]}'
    evidence = ", ".join(item.replace("-", " ") for item in record["evidence_available"]["types"])
    risks = ", ".join(item.replace("-", " ") for item in record["risk_flags"])
    risk_line = "" if risks == "none" else f'<p class="risk-row"><strong>Risk flags:</strong> {esc(risks)}</p>'
    return f'''<article class="watch-card {state}">
  <div><span class="fixture-label">Fixture</span> <span class="status-badge {'reviewed' if reviewed else 'unreviewed'}">{esc(review_label)}</span></div>
  <h3><a href="{esc(record["url"])}">{esc(record["title"])}</a></h3>
  <p class="record-meta">{esc(record["source_name"])} · {esc(record["publication_date"])} · {esc(record["source_type"].replace("-", " "))}</p>
  <p class="summary">{esc(record["short_summary"])}</p>
  <p><strong>Why it may matter</strong><br>{esc(record["reason_for_relevance"])}</p>
  {tags(labels(record["lab_themes"]))}
{risk_line}
  <div class="watch-card-footer">
    <span><strong>Source record</strong>{esc(stable_label)}</span>
    <span><strong>Evidence available</strong>{esc(evidence)}</span>
    <span><strong>Retrieved</strong>{esc(record["retrieval_date"])}</span>
    <span><strong>Confidence</strong>{esc(record["confidence"]["label"])} · {esc(record["confidence"]["score"])}</span>
  </div>
</article>'''


def generate_watch() -> None:
    approved = load_records("data/research-watch/approved")
    candidates = load_records("data/research-watch/candidates")
    write("research-watch-reviewed.qmd", '<div class="watch-grid">\n' + "\n".join(watch_card(item, "reviewed") for item in approved) + "\n</div>")
    write("research-watch-candidates.qmd", '<div class="watch-grid">\n' + "\n".join(watch_card(item, "candidate") for item in candidates) + "\n</div>")


def generate_all() -> None:
    OUT.mkdir(exist_ok=True)
    generate_themes()
    generate_people()
    generate_projects()
    generate_publications()
    generate_watch()


def main() -> int:
    errors = validate_all()
    if errors:
        print("Cannot generate site because content validation failed:")
        for error in errors:
            print(f"- {error}")
        return 1
    generate_all()
    print("Generated Quarto listing fragments from validated fixture data.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
